### ISSUE TITLE
Update guard to kirby-uniform v3

### ISSUE THREAD

**Issue by fetzi** [fetzi/kirby-uniform-recaptcha#2]
use the [CalcGuard](https://github.com/mzur/kirby-uniform/blob/b8340ee75b49705b804684da4a95ee75a9300668/src/Guards/CalcGuard.php) as a reference.

**Comment by mzur** [comment]
The [documentation on guards](http://kirby-uniform.readthedocs.io/en/v3/guards/guards/) is now ready for v3. It might be helpful :wink:
