### ISSUE TITLE
Not in composer repository

### ISSUE THREAD

**Issue by rutger1140** [fetzi/kirby-uniform-recaptcha#5]
Hi,

Is this plugin added in the composer repository? I can't seem to find it on https://packagist.org.

`The requested package fetzi/kirby-uniform-recaptcha could not be found in any version, there may be a typo in the package name.`

Cheers

**Comment by rutger1140** [comment]
Adding the tarbal as repository package directly now with this in my `composer.json`:

```
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "fetzi/kirby-uniform-recaptcha",
        "version": "1.0.0",
        "dist": {
          "type": "zip",
          "url": "https://github.com/fetzi/kirby-uniform-recaptcha/archive/master.zip"
        }
      }
    }
  ],
  "require": {
    "mzur/kirby-uniform": "^3.0",
    "fetzi/kirby-uniform-recaptcha": "1.0.0"
  }
}
```

**Comment by fetzi** [comment]
@lekkerduidelijk I've added the package to packagist. https://packagist.org/packages/fetzi/kirby-uniform-recaptcha

**Comment by rutger1140** [comment]
@fetzi Thanks! 💨
